markdown:       kramdown
highlighter:    false
#permalink:      pretty

exclude:
  - "img/old/"
  - "LICENSE.md"
  - "make.js"
  - "node_modules/"
  - "package.json"
  - "params.json"
  - "Readme.md"
  - "run-tests.js"
